### ISSUE TITLE
2_setup.sh wrong reset pin selection for ch2i V1.2 - ic880A - Raspberry PI

### ISSUE THREAD

**Issue by drucknase** [ch2i/LoraGW-Setup#7]
Hello,
I have lora gw with ch2i V1.2 board, ic880A and a RPI 3B. During running 2_setup.sh there is question, which HW combination is used for the gateway (see line 91 of 2_setup.sh). I choose "CH2i ic880a". This will select GPIO5 as reset pin for ic880A board. But this is wrong. It has to be GPIO17 for this combination. Please can you correct script. I do not know, if the selection for the other HW combinations is correct.

**Comment by drucknase** [comment]
Hello again,
because also no monitor script link is generated by 2_setup, if you select "CH2i ic880a" I did further investigations into 2_setup.sh script. After that I believe that the enumeration of the HW selection is wrong. So please check if selection of "3" should be "IMST Lora Lite (ic880a)" and selection of "4" should be  "CH2i ic880a". Then reset pin and monitor script selection would be correct at least for "CH2i ic880a". I have no documentation of "IMST Lora Lite (ic880a)" so I do not know if reset pin 5 and no monitor script is correct for this device.

**Comment by hallard** [comment]
@drucknase 
Absolutely, you're right, I swapped the menu number item, thanks for mentioning that.
